<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<base href="/" />
	<link rel="stylesheet" type="text/css" href="/css/master.css" />
	<?php 
	if ( $this->dojo()->isEnabled() ):  
		echo $this->dojo();
	endif;
	?>
</head>
<body class="tundra">
	<div id="header">
		<div id="logo">
			<img src="/images/logo.gif" />
		</div>
		<div id="menu-locale-container">
			<div id="locale">
	          <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'locale', 'action' => 'index', 'locale' => 'en_US'), 'default', true); ?>">
	            <img src="/images/locale/en_us.gif" />
	          </a>
	          <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'locale', 'action' => 'index', 'locale' => 'fil_PH'), 'default', true); ?>">
	            <img src="/images/locale/fil_ph.gif" />
	          </a>
        	</div>
			<div id="menu">
        		<?php echo $this->navigation()->menu(); ?>
        	</div>
		</div>
		
	</div>
	<div id="content">
		<?php echo $this->layout()->content ?>
	</div>
	<div id="footer">
		<p>
			<?php echo $this->translate('created-with'); ?>
				<a href="http://framework.zend.com/">
				Zend Framework</a>. 
			<?php echo $this->translate('licensed-under'); ?>
				<a href="http://www.creativecommons.org/">Creative Commons</a>.
		</p>
	</div>
</body>
</html>